/*
 * TestService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"time"
)

// User struct for User
type User struct {
	UserId NullableString `json:"user_id,omitempty"`
	NickName string `json:"nick_name"`
	ProfileImageUri NullableString `json:"profile_image_uri,omitempty"`
	Email string `json:"email"`
	Description NullableString `json:"description,omitempty"`
	SocialLink NullableString `json:"social_link,omitempty"`
	Gender NullableString `json:"gender,omitempty"`
	IdentifyStatus NullableString `json:"identify_status,omitempty"`
	CustomerId NullableString `json:"customer_id,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	DeletedAt NullableTime `json:"deleted_at,omitempty"`
}

// NewUser instantiates a new User object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUser(nickName string, email string, createdAt time.Time, updatedAt time.Time, ) *User {
	this := User{}
	this.NickName = nickName
	this.Email = email
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewUserWithDefaults instantiates a new User object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWithDefaults() *User {
	this := User{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetUserId() string {
	if o == nil || o.UserId.Get() == nil {
		var ret string
		return ret
	}
	return *o.UserId.Get()
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetUserIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.UserId.Get(), o.UserId.IsSet()
}

// HasUserId returns a boolean if a field has been set.
func (o *User) HasUserId() bool {
	if o != nil && o.UserId.IsSet() {
		return true
	}

	return false
}

// SetUserId gets a reference to the given NullableString and assigns it to the UserId field.
func (o *User) SetUserId(v string) {
	o.UserId.Set(&v)
}
// SetUserIdNil sets the value for UserId to be an explicit nil
func (o *User) SetUserIdNil() {
	o.UserId.Set(nil)
}

// UnsetUserId ensures that no value is present for UserId, not even an explicit nil
func (o *User) UnsetUserId() {
	o.UserId.Unset()
}

// GetNickName returns the NickName field value
func (o *User) GetNickName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.NickName
}

// GetNickNameOk returns a tuple with the NickName field value
// and a boolean to check if the value has been set.
func (o *User) GetNickNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NickName, true
}

// SetNickName sets field value
func (o *User) SetNickName(v string) {
	o.NickName = v
}

// GetProfileImageUri returns the ProfileImageUri field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetProfileImageUri() string {
	if o == nil || o.ProfileImageUri.Get() == nil {
		var ret string
		return ret
	}
	return *o.ProfileImageUri.Get()
}

// GetProfileImageUriOk returns a tuple with the ProfileImageUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetProfileImageUriOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ProfileImageUri.Get(), o.ProfileImageUri.IsSet()
}

// HasProfileImageUri returns a boolean if a field has been set.
func (o *User) HasProfileImageUri() bool {
	if o != nil && o.ProfileImageUri.IsSet() {
		return true
	}

	return false
}

// SetProfileImageUri gets a reference to the given NullableString and assigns it to the ProfileImageUri field.
func (o *User) SetProfileImageUri(v string) {
	o.ProfileImageUri.Set(&v)
}
// SetProfileImageUriNil sets the value for ProfileImageUri to be an explicit nil
func (o *User) SetProfileImageUriNil() {
	o.ProfileImageUri.Set(nil)
}

// UnsetProfileImageUri ensures that no value is present for ProfileImageUri, not even an explicit nil
func (o *User) UnsetProfileImageUri() {
	o.ProfileImageUri.Unset()
}

// GetEmail returns the Email field value
func (o *User) GetEmail() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *User) GetEmailOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *User) SetEmail(v string) {
	o.Email = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *User) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *User) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *User) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *User) UnsetDescription() {
	o.Description.Unset()
}

// GetSocialLink returns the SocialLink field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetSocialLink() string {
	if o == nil || o.SocialLink.Get() == nil {
		var ret string
		return ret
	}
	return *o.SocialLink.Get()
}

// GetSocialLinkOk returns a tuple with the SocialLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetSocialLinkOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SocialLink.Get(), o.SocialLink.IsSet()
}

// HasSocialLink returns a boolean if a field has been set.
func (o *User) HasSocialLink() bool {
	if o != nil && o.SocialLink.IsSet() {
		return true
	}

	return false
}

// SetSocialLink gets a reference to the given NullableString and assigns it to the SocialLink field.
func (o *User) SetSocialLink(v string) {
	o.SocialLink.Set(&v)
}
// SetSocialLinkNil sets the value for SocialLink to be an explicit nil
func (o *User) SetSocialLinkNil() {
	o.SocialLink.Set(nil)
}

// UnsetSocialLink ensures that no value is present for SocialLink, not even an explicit nil
func (o *User) UnsetSocialLink() {
	o.SocialLink.Unset()
}

// GetGender returns the Gender field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetGender() string {
	if o == nil || o.Gender.Get() == nil {
		var ret string
		return ret
	}
	return *o.Gender.Get()
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetGenderOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Gender.Get(), o.Gender.IsSet()
}

// HasGender returns a boolean if a field has been set.
func (o *User) HasGender() bool {
	if o != nil && o.Gender.IsSet() {
		return true
	}

	return false
}

// SetGender gets a reference to the given NullableString and assigns it to the Gender field.
func (o *User) SetGender(v string) {
	o.Gender.Set(&v)
}
// SetGenderNil sets the value for Gender to be an explicit nil
func (o *User) SetGenderNil() {
	o.Gender.Set(nil)
}

// UnsetGender ensures that no value is present for Gender, not even an explicit nil
func (o *User) UnsetGender() {
	o.Gender.Unset()
}

// GetIdentifyStatus returns the IdentifyStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetIdentifyStatus() string {
	if o == nil || o.IdentifyStatus.Get() == nil {
		var ret string
		return ret
	}
	return *o.IdentifyStatus.Get()
}

// GetIdentifyStatusOk returns a tuple with the IdentifyStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetIdentifyStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.IdentifyStatus.Get(), o.IdentifyStatus.IsSet()
}

// HasIdentifyStatus returns a boolean if a field has been set.
func (o *User) HasIdentifyStatus() bool {
	if o != nil && o.IdentifyStatus.IsSet() {
		return true
	}

	return false
}

// SetIdentifyStatus gets a reference to the given NullableString and assigns it to the IdentifyStatus field.
func (o *User) SetIdentifyStatus(v string) {
	o.IdentifyStatus.Set(&v)
}
// SetIdentifyStatusNil sets the value for IdentifyStatus to be an explicit nil
func (o *User) SetIdentifyStatusNil() {
	o.IdentifyStatus.Set(nil)
}

// UnsetIdentifyStatus ensures that no value is present for IdentifyStatus, not even an explicit nil
func (o *User) UnsetIdentifyStatus() {
	o.IdentifyStatus.Unset()
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetCustomerId() string {
	if o == nil || o.CustomerId.Get() == nil {
		var ret string
		return ret
	}
	return *o.CustomerId.Get()
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetCustomerIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.CustomerId.Get(), o.CustomerId.IsSet()
}

// HasCustomerId returns a boolean if a field has been set.
func (o *User) HasCustomerId() bool {
	if o != nil && o.CustomerId.IsSet() {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given NullableString and assigns it to the CustomerId field.
func (o *User) SetCustomerId(v string) {
	o.CustomerId.Set(&v)
}
// SetCustomerIdNil sets the value for CustomerId to be an explicit nil
func (o *User) SetCustomerIdNil() {
	o.CustomerId.Set(nil)
}

// UnsetCustomerId ensures that no value is present for CustomerId, not even an explicit nil
func (o *User) UnsetCustomerId() {
	o.CustomerId.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *User) GetCreatedAt() time.Time {
	if o == nil  {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *User) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *User) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *User) GetUpdatedAt() time.Time {
	if o == nil  {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *User) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *User) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetDeletedAt() time.Time {
	if o == nil || o.DeletedAt.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt.Get()
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.DeletedAt.Get(), o.DeletedAt.IsSet()
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *User) HasDeletedAt() bool {
	if o != nil && o.DeletedAt.IsSet() {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given NullableTime and assigns it to the DeletedAt field.
func (o *User) SetDeletedAt(v time.Time) {
	o.DeletedAt.Set(&v)
}
// SetDeletedAtNil sets the value for DeletedAt to be an explicit nil
func (o *User) SetDeletedAtNil() {
	o.DeletedAt.Set(nil)
}

// UnsetDeletedAt ensures that no value is present for DeletedAt, not even an explicit nil
func (o *User) UnsetDeletedAt() {
	o.DeletedAt.Unset()
}

func (o User) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UserId.IsSet() {
		toSerialize["user_id"] = o.UserId.Get()
	}
	if true {
		toSerialize["nick_name"] = o.NickName
	}
	if o.ProfileImageUri.IsSet() {
		toSerialize["profile_image_uri"] = o.ProfileImageUri.Get()
	}
	if true {
		toSerialize["email"] = o.Email
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.SocialLink.IsSet() {
		toSerialize["social_link"] = o.SocialLink.Get()
	}
	if o.Gender.IsSet() {
		toSerialize["gender"] = o.Gender.Get()
	}
	if o.IdentifyStatus.IsSet() {
		toSerialize["identify_status"] = o.IdentifyStatus.Get()
	}
	if o.CustomerId.IsSet() {
		toSerialize["customer_id"] = o.CustomerId.Get()
	}
	if true {
		toSerialize["created_at"] = o.CreatedAt
	}
	if true {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if o.DeletedAt.IsSet() {
		toSerialize["deleted_at"] = o.DeletedAt.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableUser struct {
	value *User
	isSet bool
}

func (v NullableUser) Get() *User {
	return v.value
}

func (v *NullableUser) Set(val *User) {
	v.value = val
	v.isSet = true
}

func (v NullableUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUser(val *User) *NullableUser {
	return &NullableUser{value: val, isSet: true}
}

func (v NullableUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
